name: NITTS Webinar
url: http://localhost:4000
markdown: kramdown
permalink: /blog/:title
sass:
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jemoji
